version: "3"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - API_KEY=<api_key>
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/<website>/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/<website>/privkey.pem:/etc/ssl/private/privkey.pem
    depends_on:
      - web
