openapi: 3.0.1
info:
  title: ChatGPT Plugin
  description: A plugin that allows the user to interact with a conversational retrieval model using ChatGPT.
  version: "v1"
servers:
  - url: http://localhost:4444

paths:
  /chat:
    post:
      operationId: chat
      summary: Interact with the conversational retrieval model
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Message"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"

components:
  schemas:
    Message:
      type: object
      required:
        - query
      properties:
        query:
          type: string
          description: The query to send to the conversational retrieval model.
    Result:
      type: object
      properties:
        answer:
          type: string
          description: The answer from the conversational retrieval model.
